import { HeuristicArchitect } from './architect';
import { RegexExtractor } from './extractor';
import { createDefaultResolvers, ResolverRegistry } from './resolvers';
import { ParseratorSession } from './session';
import { createTelemetryHub, TelemetryHub } from './telemetry';
import { ArchitectAgent, BatchParseOptions, ExtractorAgent, ParseRequest, ParseResponse, ParseratorCoreConfig, ParseratorCoreOptions, ParseratorProfileOption, ParseratorSessionInit, ParseratorInterceptor } from './types';
export * from './types';
export * from './profiles';
export { ParseratorSession } from './session';
export declare class ParseratorCore {
    private readonly apiKey;
    private config;
    private logger;
    private architect;
    private extractor;
    private resolverRegistry;
    private profileName?;
    private profileOverrides;
    private configOverrides;
    private telemetry;
    private readonly interceptors;
    constructor(options: ParseratorCoreOptions);
    updateConfig(partial: Partial<ParseratorCoreConfig>): void;
    getConfig(): ParseratorCoreConfig;
    getProfile(): string | undefined;
    applyProfile(profile: ParseratorProfileOption): void;
    static profiles(): import("./types").ParseratorProfile[];
    setArchitect(agent: ArchitectAgent): void;
    setExtractor(agent: ExtractorAgent): void;
    registerResolver(resolver: Parameters<ResolverRegistry['register']>[0], position?: 'append' | 'prepend'): void;
    replaceResolvers(resolvers: Parameters<ResolverRegistry['register']>[0][]): void;
    listResolvers(): string[];
    use(interceptor: ParseratorInterceptor): () => void;
    listInterceptors(): ParseratorInterceptor[];
    createSession(init: ParseratorSessionInit): ParseratorSession;
    private composeConfig;
    parse(request: ParseRequest): Promise<ParseResponse>;
    parseMany(requests: ParseRequest[], options?: BatchParseOptions): Promise<ParseResponse[]>;
    private getInterceptors;
    private runBeforeInterceptors;
    private runAfterInterceptors;
    private runFailureInterceptors;
    private handleArchitectFailure;
    private handleExtractorFailure;
    private attachRegistryIfSupported;
}
export { HeuristicArchitect, RegexExtractor, ResolverRegistry, createDefaultResolvers, createTelemetryHub, TelemetryHub };
//# sourceMappingURL=index.d.ts.map