export declare const SHARED_PLAN_KEY = "parserator-core:plan";
export declare const SHARED_SCHEMA_KEY = "parserator-core:schema";
export declare const SHARED_INSTRUCTIONS_KEY = "parserator-core:instructions";
export declare const SHARED_REQUEST_ID_KEY = "parserator-core:request-id";
export declare const SHARED_SESSION_ID_KEY = "parserator-core:session-id";
export declare const SHARED_PROFILE_KEY = "parserator-core:profile";
export declare const SHARED_RESOLVED_FIELD_PREFIX = "parserator-core:resolved-field:";
export declare const SHARED_LEAN_FALLBACK_PROMISE_KEY = "parserator-core:lean-llm-fallback:promise";
export declare const SHARED_LEAN_FALLBACK_RESULT_KEY = "parserator-core:lean-llm-fallback:result";
//# sourceMappingURL=resolver-constants.d.ts.map