export declare const SHARED_PLAN_KEY = "parserator-core:plan";
export declare const SHARED_SCHEMA_KEY = "parserator-core:schema";
export declare const SHARED_INSTRUCTIONS_KEY = "parserator-core:instructions";
export declare const SHARED_REQUEST_ID_KEY = "parserator-core:request-id";
export declare const SHARED_SESSION_ID_KEY = "parserator-core:session-id";
export declare const SHARED_PROFILE_KEY = "parserator-core:profile";
export declare const SHARED_LEAN_LLM_RESULTS_KEY = "parserator-core:lean-llm:results";
export declare const SHARED_LEAN_LLM_PENDING_KEY = "parserator-core:lean-llm:pending";
export declare const SHARED_LEAN_LLM_LAST_CALL_KEY = "parserator-core:lean-llm:last-call";
export declare const SHARED_LEAN_LLM_LAST_ERROR_KEY = "parserator-core:lean-llm:last-error";
export declare const SHARED_RESOLVED_FIELD_PREFIX = "parserator-core:resolved-field:";
//# sourceMappingURL=resolver-constants.d.ts.map